stages:    
  - test
  - build
  - deploy

build-job:    
  stage: build
  script:
    - docker build -t shortest-path .

test-job:
  stage: test
  script: 
    - docker run --rm shortest-path mvn test
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/TEST-*.xml
    paths:
      - target/surefire-reports/
      
deploy-job:    
  stage: deploy
  script:
    - docker compose up -d
